//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Genres')
export class GenresEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  genreName: string;
}
