//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Scripts')
export class ScriptsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  genre: string;

  @Column('integer', { nullable: true })
  length: number;

  @Column('text', { nullable: true })
  scriptText: string;
}
