//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="AI Script and eBook Generator" />
    <CardContent>
      The app generates full and short movie scripts, TV series scripts of all
      genres, and short storybooks and novels with images. Users must create an
      account or sign in with Gmail and pay a monthly fee of $10 or annually
      $100.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
